import { Camera, Check, Leaf, Sparkles } from "./Icons";

const steps = [
  { number: "01", icon: Camera, title: "Take or upload a photo", text: "Show us the item you’re unsure about. A quick snapshot is all it takes." },
  { number: "02", icon: Sparkles, title: "AI identifies the waste", text: "Our analysis looks at the item and surfaces a useful, easy-to-understand estimate." },
  { number: "03", icon: Check, title: "Get your next step", text: "See what it’s made of, if it can be recycled, and how to dispose of it responsibly." },
];

export function HowItWorks() {
  return <section className="border-y border-[#e1ebe2] bg-white/60" id="how-it-works"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><div className="max-w-xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#368256]">The simple loop</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.05em] text-[#183c2b] sm:text-5xl">From photo to<br />positive impact.</h2></div><div className="mt-14 grid gap-5 md:grid-cols-3">{steps.map((step) => <article className="group rounded-3xl border border-[#e0ebe1] bg-[#fbfdfb] p-7 transition-all hover:-translate-y-1 hover:border-[#b7dcbf] hover:shadow-xl hover:shadow-[#357b4d]/8" key={step.number}><div className="flex items-center justify-between"><div className="flex size-12 items-center justify-center rounded-2xl bg-[#e4f3e7] text-[#2c7b4b]"><step.icon className="size-5" /></div><span className="text-sm font-semibold text-[#c0d5c4]">{step.number}</span></div><h3 className="mt-9 text-xl font-semibold tracking-[-0.03em] text-[#244a34]">{step.title}</h3><p className="mt-3 leading-7 text-[#718378]">{step.text}</p></article>)}</div><div className="mt-16 flex flex-col gap-5 rounded-3xl bg-[#e9f5ea] px-6 py-7 sm:flex-row sm:items-center sm:justify-between sm:px-9"><div className="flex items-start gap-4"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-white text-[#368256]"><Leaf className="size-5" /></div><div><p className="font-semibold text-[#245439]">Built on a thoughtful technology stack</p><p className="mt-1 text-sm leading-6 text-[#62806c]">Amazon S3, AWS Lambda, and Amazon Bedrock will power the full experience as we grow.</p></div></div><span className="shrink-0 rounded-full border border-[#c5e1ca] bg-white/60 px-4 py-2 text-xs font-semibold text-[#39704d]">Integration-ready MVP</span></div></div></section>;
}
